// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldIsActivated holds the string denoting the isactivated field in the database.
	FieldIsActivated = "is_activated"
	// EdgeProducts holds the string denoting the products edge name in mutations.
	EdgeProducts = "products"
	// Table holds the table name of the user in the database.
	Table = "users"
	// ProductsTable is the table the holds the products relation/edge.
	ProductsTable = "tour_products"
	// ProductsInverseTable is the table name for the TourProduct entity.
	// It exists in this package in order to avoid circular dependency with the "tourproduct" package.
	ProductsInverseTable = "tour_products"
	// ProductsColumn is the table column denoting the products relation/edge.
	ProductsColumn = "user_products"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldIsActivated,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsActivated holds the default value on creation for the "isActivated" field.
	DefaultIsActivated bool
)
