// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package main

import (
	mock "github.com/stretchr/testify/mock"
	ent "github.com/umi0410/how-to-backend-in-go/testcode/ent"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: input
func (_m *MockUserRepository) Create(input *UserCreateInput) (*ent.User, error) {
	ret := _m.Called(input)

	var r0 *ent.User
	if rf, ok := ret.Get(0).(func(*UserCreateInput) *ent.User); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*UserCreateInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
