// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// TourProduct is the predicate function for tourproduct builders.
type TourProduct func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
