// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"db/ent/predicate"
	"db/ent/tourproduct"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TourProductDelete is the builder for deleting a TourProduct entity.
type TourProductDelete struct {
	config
	hooks    []Hook
	mutation *TourProductMutation
}

// Where adds a new predicate to the TourProductDelete builder.
func (tpd *TourProductDelete) Where(ps ...predicate.TourProduct) *TourProductDelete {
	tpd.mutation.predicates = append(tpd.mutation.predicates, ps...)
	return tpd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tpd *TourProductDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(tpd.hooks) == 0 {
		affected, err = tpd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TourProductMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tpd.mutation = mutation
			affected, err = tpd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tpd.hooks) - 1; i >= 0; i-- {
			mut = tpd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tpd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (tpd *TourProductDelete) ExecX(ctx context.Context) int {
	n, err := tpd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tpd *TourProductDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: tourproduct.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tourproduct.FieldID,
			},
		},
	}
	if ps := tpd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, tpd.driver, _spec)
}

// TourProductDeleteOne is the builder for deleting a single TourProduct entity.
type TourProductDeleteOne struct {
	tpd *TourProductDelete
}

// Exec executes the deletion query.
func (tpdo *TourProductDeleteOne) Exec(ctx context.Context) error {
	n, err := tpdo.tpd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tourproduct.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tpdo *TourProductDeleteOne) ExecX(ctx context.Context) {
	tpdo.tpd.ExecX(ctx)
}
